#!/bin/sh

ticket_regex="^se-\d+"

commit_message=$(cat "$1")

if ! echo "$commit_message" | grep -qE "$ticket_regex"; then
    echo "Error: Commit message must contain a ticket number in the format 'se-1234'."
    exit 1
fi

exit 0
